name: CIEDE 2000 32/64 bits identity

on:
  schedule:
    - cron: '16 1 7,21 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard verifies 32-bit and 64-bit ΔE2000 implementations in C and C++"
  process: "The program internally verifies that the languages ​​produce identical results and displays a summary"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/cpp"

jobs:
  test-delta-e-2000-identity:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up g++
        run:  command -v g++ > /dev/null || { sudo apt-get update && sudo apt-get install -y g++ ; }

      - name: 🔧 Initialize the C99 and C++ source files
        run: |
          dir="tests/cpp"
          sed 's/ciede_2000/ciede_2000_c_double/' ciede-2000.c > $dir/prelude.cpp
          sed 's/ciede_2000/ciede_2000_c_float/' tests/c/ciede-2000-single-precision.c >> $dir/prelude.cpp
          sed 's/ciede_2000/ciede_2000_cpp/' ciede-2000.cpp >> $dir/prelude.cpp

      - name: ℹ️ Initialize the contents of summary.txt with the system signature
        run: |
          echo -e "=============== System Signature ================\n" \
          "Hostname     : "$(cat /proc/sys/kernel/hostname) "\n" \
          "OS           : "$(cat /proc/sys/kernel/ostype) $(cat /proc/sys/kernel/osrelease) "\n" \
          "Architecture : "$(uname -m) "\n" \
          "CPU          : "$(grep -m1 'model name' /proc/cpuinfo | cut -d ':' -f2 | sed 's/^ //') "\n" \
          "Cores        : "$(nproc) "\n" \
          "Memory       : "$(awk '/MemTotal/ {printf "%.1f GB", $2/1024/1024}' /proc/meminfo) "\n" \
          "================================================" > summary.txt

      - name: ☁️ Upload source code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: prelude.cpp
          path: tests/cpp/prelude.cpp
          retention-days: 14

      - name: ⚙️ Compile the CIEDE2000 testing program in C++
        run: g++ --version && g++ -std=c++14 -Wall -Wextra -Wpedantic -Ofast -o ciede-2000-identity tests/cpp/ciede-2000-identity.cpp

      - name: 🚀 Run tests and confirm that C and C++ implementations are equals
        run: ./ciede-2000-identity 80000000 >> summary.txt 2>&1

      - name: 🔍 Display verification output
        run: cat summary.txt

      - name: 🏁 Conclusion
        run: |
          if grep -q "Status: PASS - All implementations" summary.txt; then
            echo "✔️ Verification successful: all color differences were correctly calculated."
          else
            echo "❌ Verification failed. See above for details."
            exit 1
          fi

      - name: 🔼 Upload summary.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: summary.txt
          retention-days: 60
