name: Python CIEDE2000 Testing

on:
  schedule:
    - cron: '5 21 3,17 * *'
  workflow_dispatch:

jobs:
  test-ciede-2000-py:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 🔧 Install GCC
        run: command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }

      - name: ⚙️ Compile the CIEDE2000 verification program in C99
        run: gcc --version && gcc -O3 tests/c/stdin-verifier.c -o verifier -lm

      - name: 🧪 Generate ΔE2000 test cases and stream to C99 verifier
        run: python3 --version && python3 tests/py/ciede-2000-testing.py 10000000 | ./verifier > test-output.txt

      - name: 🔍 Display verification output
        run: cat test-output.txt

      - name: ✅ Conclusion
        run: |
          if grep -q "Errors : 0" test-output.txt && ! grep -q "Successes : 0" test-output.txt; then
            echo "✅ Verification successful: All color differences were correctly calculated."
          else
            echo "❌ Verification failed: Please check the previous step."
            exit 1
          fi
