name: D CIEDE2000 Testing

on:
  schedule:
    - cron: '30 2 2,16 * *'
  workflow_dispatch:

jobs:
  test-ciede-2000-d:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up D compiler (LDC)
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest

      - name: Prepare the file to be compiled
        run: cp -p tests/d/ciede-2000-testing.d tests/d/main.d

      - name: 🔧 Install GCC
        run: command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }

      - name: ⚙️ Compile CIEDE2000 tester
        run: ldc2 -version && ldc2 -O -release -boundscheck=off -of=ciede2000-test tests/d/main.d

      - name: 🛠️ Compile the CIEDE2000 verification program in C99
        run: gcc --version && gcc -O3 tests/c/stdin-verifier.c -o verifier -lm

      - name: 🧪 Generate ΔE2000 test cases and stream to C99 verifier
        run: ./ciede2000-test 10000000 | ./verifier > test-output.txt

      - name: 🔍 Display verification output
        run: cat test-output.txt

      - name: ✅ Conclusion
        run: |
          if grep -q "Errors : 0" test-output.txt && ! grep -q "Successes : 0" test-output.txt; then
            echo "✅ Verification successful: All color differences were correctly calculated."
          else
            echo "❌ Verification failed: Please check the previous step."
            exit 1
          fi
