name: Nim CIEDE2000 Testing

on:
  schedule:
    - cron: '1 22 4,19 * *'
  workflow_dispatch:

jobs:
  test-ciede-2000-nim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nim
        uses: iffy/install-nim@v5
        with:
          version: stable

      - name: Run ΔE2000 testing and verify output
        run: nim c --opt:speed -r tests/nim/ciede_2000_testing.nim 5000000 | node .github/workflows/scripts/stdin-verifier.js > test-output.txt

      - name: 🔍 Display verification output
        run: cat test-output.txt

      - name: Conclusion
        run: |
          if grep -q "Errors : 0" test-output.txt && ! grep -q "Successes : 0" test-output.txt; then
            echo "✅ Verification successful: Output meets expected criteria."
          else
            echo "❌ Verification failed: Please check the test output."
            exit 1
          fi
