name: Nim CIEDE2000 Testing

on:
  schedule:
    - cron: '5 3 3,17 * *'
  workflow_dispatch:

jobs:
  test-ciede-2000-nim:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nim
        uses: iffy/install-nim@v5
        with:
          version: stable

      - name: ⚙️ Set Up the Nim testing file
        run: mv tests/nim/ciede-2000-testing.nim tests/nim/ciede_2000_testing.nim

      - name: 🔧 Install GCC
        run: command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }

      - name: ⚙️ Compile the CIEDE2000 verification program in C99
        run: gcc --version && gcc -O3 tests/c/stdin-verifier.c -o verifier -lm

      - name: 🧪 Generate ΔE2000 test cases and stream to C99 verifier
        run: nim -v && nim c --opt:speed -r tests/nim/ciede_2000_testing.nim 10000000 | ./verifier > test-output.txt

      - name: 🔍 Display verification output
        run: cat test-output.txt

      - name: ✅ Conclusion
        run: |
          if grep -q "Errors : 0" test-output.txt && ! grep -q "Successes : 0" test-output.txt; then
            echo "✅ Verification successful: All color differences were correctly calculated."
          else
            echo "❌ Verification failed: Please check the previous step."
            exit 1
          fi
