name: Swift CIEDE2000 Testing

on:
  schedule:
    - cron: '3 22 2,17 * *'
  workflow_dispatch:

jobs:
  test-ciede-2000-swift:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift
        run: swift --version

      - name: Run ΔE2000 testing and verify output
        run: swift tests/swift/ciede-2000-testing.swift 5000000 | node .github/workflows/scripts/stdin-verifier.js > test-output.txt

      - name: 🔍 Display verification output
        run: cat test-output.txt

      - name: Conclusion
        run: |
          if grep -q "Errors : 0" test-output.txt && ! grep -q "Successes : 0" test-output.txt; then
            echo "✅ Verification successful: Output meets expected criteria."
          else
            echo "❌ Verification failed: Please check the test output."
            exit 1
          fi
