name: C99 CIEDE2000 Testing

# When this workflow was tested, its execution produced a success in 36 seconds.

on:
  schedule:
    - cron: '43 2 6,20 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard implements the CIE2000 color difference formula in C99"
  input_file: "test-cases.csv contains lines like 13.6,98,6,24,40,-20.4 representing two L*a*b* colors"
  process:  "Print the line with its Delta E like 13.6,98,6,24,40,-20.4,19.959401086016186808570466797025 for each line"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/c"
  n_csv_lines: 10000000

jobs:
  test-implementation-de00-c:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up Node and GCC
        run: |
          command -v node > /dev/null || { sudo apt-get update && sudo apt-get install -y nodejs ; }
          command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }

      - name: ⚙️ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -O2 -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: 📑 Display help for the authoritative test software
        run: ./ciede-2000-driver --help

      - name: 🎨 Generate ΔE2000 color difference test cases
        run: ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines --output-file test-cases.csv

      - name: 🚀 Run C tests and verify with Node.js
        run: node --version && ./ciede-2000-driver -s -i test-cases.csv | node tests/js/ciede-2000-driver.js > summary.txt

      - name: 🔍 Display verification output
        run: cat summary.txt

      - name: 🏁 Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "✔️ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "❌ Verification failed. See above for details."
            exit 1
          fi
