name: Wren CIEDE2000 Testing

on:
  schedule:
    - cron: '48 11 3,17 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard implements the CIE2000 color difference formula in Wren."
  input_file: "test-cases.csv contains lines like 74,46.4,114.1,71.6,11,82 representing two L*a*b* colors"
  process:  "Print the line with its Delta E like 74,46.4,114.1,71.6,11,82,15.3404963375093 for each line"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/wren"
  n_csv_lines: 10000000

jobs:
  test-delta-e-2000-wren:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up Wren and GCC
        run: |
          command -v make > /dev/null || { sudo apt-get update && sudo apt-get install -y make ; }
          git clone --depth 1 https://github.com/wren-lang/wren-cli.git
          # The cd is scoped into a subshell, so not persistent.
          (cd wren-cli/projects/make && make -f wren_cli.make)
          echo "$PWD/wren-cli/bin" >> $GITHUB_PATH
          command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }

      - name: ⚙️ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -Ofast -ffast-math -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: 🎨 Generate ΔE2000 color difference test cases (split into 50k-line files)
        run: ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines | split -u -l 50000 - X

      - name: 🚀 Run test cases in Wren and stream to verifier
        run: |
          file_list=$(ls X* | tr '\n' ' ')
          wren_cli --version && wren_cli tests/wren/ciede-2000-driver.wren $file_list | ./ciede-2000-driver -o summary.txt

      - name: 🔍 Display verification output
        run: cat summary.txt

      - name: 🏁 Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "✔️ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "❌ Verification failed. See above for details."
            exit 1
          fi
