name: bc CIEDE2000 Testing (arbitrary prec.)

# When this workflow was tested, its execution produced a success in 200 seconds.

on:
  schedule:
    - cron: '20 0 2,16 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard implements the CIE2000 color difference formula in bc and Julia"
  related_url_1: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/bc"
  related_url_2: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/jl"
  n_csv_lines: 100000
  decimal_digits: 30

jobs:
  test-implementation-de00-bc-arbitrary:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up Julia, bc and GCC
        run: |
          command -v bc > /dev/null || { sudo apt-get update && sudo apt-get install -y bc ; }
          if ! command -v julia > /dev/null; then
          	########################################################################################
          	####  STEP 1:            Download & Extract the latest version of Julia             ####
          	########################################################################################
          	URL=$(wget -qO- https://julialang.org/downloads/ | grep 'linux/x64' |
          	grep '\.tar\.gz' | grep -o 'https://[^"]*' | head -n 1)
          	if [ -z "$URL" ]; then
          		URL="https://julialang-s3.julialang.org/bin/linux/x64/1.11/julia-1.11.5-linux-x86_64.tar.gz"
          	fi
          	rm -rf /opt/julia
          	mkdir /opt/julia
          	wget -q -T5 -t3 -O- "$URL" | tar -xz --strip-components=1 -C /opt/julia
          	########################################################################################
          	####  STEP 2:                       Add Julia to System PATH                        ####
          	########################################################################################
          	sudo ln -sf /opt/julia/bin/julia /usr/local/bin/julia
          	########################################################################################
          	####  CONCLUSION:                    Julia Installed in Under 15s                   ####
          	########################################################################################
          fi
          julia --version
          command -v bc > /dev/null || { sudo apt-get update && sudo apt-get install -y bc ; }
          command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }

      - name: ⚙️ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -O2 -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: 📑 Display help for the authoritative test software
        run: ./ciede-2000-driver --help

      - name: 🎨 Generate ΔE2000 color difference test cases
        run: ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines --output-file test-cases.csv

      - name: 🔧 Prepares high-precision ΔE2000 results with bc (Basic Calculator)
        run: |
          bc --version
          # Prevent line breaks in bc output.
          export BC_LINE_LENGTH=0
          awk -F ',' '                                                   \
          BEGIN {                                                        \
              # Define the scale.                                        \
              print "scale=" int(1.5 * '$decimal_digits');               \
                                                                         \
              # Includes the ciede-2000.bc file.                         \
              while ((getline line < "ciede-2000.bc") > 0) print line;   \
                                                                         \
          } {                                                            \
                                                                         \
              # Convert CSV lines into bc input format.                  \
              gsub(/[eE]/, "*10^", $0);                                  \
              printf("ciede_2000(%s)\n", $0);                            \
                                                                         \
          }' test-cases.csv | bc -ql > bc-answer.raw

      - name: 🚀 Check that Julia’s generic high-precision calculations matches bc's
        run: paste -d ',' test-cases.csv bc-answer.raw | julia tests/jl/ciede-2000-driver.jl --tolerance 1e-$decimal_digits > summary.txt

      - name: 🔍 Display verification output
        run: cat summary.txt

      - name: 🏁 Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "✔️ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "❌ Verification failed. See above for details."
            exit 1
          fi
