name: D CIEDE2000 Testing

on:
  schedule:
    - cron: '30 2 2,16 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard implements the CIE2000 color difference formula in D."
  input_file: "test-cases.csv contains lines like 74,46.4,114.1,71.6,11,82 representing two L*a*b* colors"
  process:  "Print the line with its Delta E like 74,46.4,114.1,71.6,11,82,15.3404963375093 for each line"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/d"
  n_csv_lines: 10000000

jobs:
  test-delta-e-2000-d:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up D compiler (LDC)
        uses: dlang-community/setup-dlang@v1
        continue-on-error: true
        timeout-minutes: 1
        with:
          compiler: ldc-latest

      - name: 📦 Set up LDC and GCC
        run: |
          command -v ldc2 > /dev/null || { sudo apt-get update && sudo apt-get install -y ldc ; }
          command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }

      - name: ⚙️ Compile CIEDE2000 tester in D
        run: |
          cp -p tests/d/ciede-2000-driver.d tests/d/main.d
          ldc2 -version && ldc2 -O -release -boundscheck=off -of=ciede2000-test tests/d/main.d

      - name: ⚙️ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -Ofast -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: 🎨 Generate ΔE2000 color difference test cases
        run: ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines --output-file test-cases.csv

      - name: 🚀 Run test cases in D and stream to verifier
        run: ./ciede2000-test test-cases.csv | ./ciede-2000-driver -o summary.txt

      - name: 🔍 Display verification output
        run: cat summary.txt

      - name: 🏁 Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "✔️ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "❌ Verification failed. See above for details."
            exit 1
          fi
