name: Dart CIEDE2000 Testing

on:
  schedule:
    - cron: '8 11 10,24 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard implements the CIE2000 color difference formula in Dart."
  input_file: "test-cases.csv contains lines like 74,46.4,114.1,71.6,11,82 representing two L*a*b* colors"
  process:  "Print the line with its Delta E like 74,46.4,114.1,71.6,11,82,15.3404963375093 for each line"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/dart"
  n_csv_lines: 10000000

jobs:
  test-delta-e-2000-dart:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up Dart
        uses: dart-lang/setup-dart@v1
        continue-on-error: true
        timeout-minutes: 1
        with:
          sdk: stable

      - name: 📦 Set up Dart and GCC
        run: |
          if ! command -v dart > /dev/null; then
            wget --timeout=5 --tries=2 -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub \
            | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
            echo "deb [signed-by=/usr/share/keyrings/dart.gpg]" \
            "https://storage.googleapis.com/download.dartlang.org/linux/debian stable main" \
            | sudo tee /etc/apt/sources.list.d/dart_stable.list
            sudo apt-get update
            sudo apt-get install -y dart
            # sudo ln -s /usr/lib/dart/bin/dart /usr/local/bin/dart
            echo "/usr/lib/dart/bin" >> $GITHUB_PATH
          fi
          command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }

      - name: ⚙️ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -Ofast -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: 🎨 Generate ΔE2000 color difference test cases
        run: ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines --output-file test-cases.csv

      - name: 🚀 Run test cases in Dart and stream to verifier
        run: dart --version && dart tests/dart/ciede-2000-driver.dart test-cases.csv | ./ciede-2000-driver -o summary.txt

      - name: 🔍 Display verification output
        run: cat summary.txt

      - name: 🏁 Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "✔️ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "❌ Verification failed. See above for details."
            exit 1
          fi
