name: TCL CIEDE2000 Testing

# When this workflow was tested, its execution produced a success in 149 seconds.

on:
  schedule:
    - cron: '1 11 5,19 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard implements the CIE2000 color difference formula in TCL"
  input_file: "test-cases.csv contains lines like 35.6,-5,98.7,4,2,86 representing two L*a*b* colors"
  process:  "Print the line with its Delta E like 35.6,-5,98.7,4,2,86,22.263920034760244006020346225024 for each line"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/tcl"
  n_csv_lines: 10000000

jobs:
  test-implementation-de00-tcl:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up TCL (Tool Command Language) and GCC
        run: |
          command -v tclsh > /dev/null || { sudo apt-get update && sudo apt-get install -y tcl ; }
          command -v gcc > /dev/null || { sudo apt-get update && sudo apt-get install -y gcc ; }
          echo 'puts $tcl_version' | tclsh

      - name: ⚙️ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -O2 -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: 📑 Display help for the authoritative test software
        run: ./ciede-2000-driver --help

      - name: 🎨 Generate ΔE2000 color difference test cases
        run: ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines --output-file test-cases.csv

      - name: 🚀 Run test cases in TCL and stream to verifier
        run: tclsh tests/tcl/ciede-2000-driver.tcl test-cases.csv | ./ciede-2000-driver -o summary.txt

      - name: 🔍 Display verification output
        run: cat summary.txt

      - name: 🏁 Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "✔️ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "❌ Verification failed. See above for details."
            exit 1
          fi
