name: Prolog CIEDE2000 Testing

# During summer 2025, this workflow was tested on several weekends and completed successfully in 84 seconds.

on:
  schedule:
    - cron: '24 4 3,17 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard implements the CIE2000 color difference formula in Prolog"
  input_file: "test-cases.csv contains lines like 42.2,67,-23.3,55,30,2 representing two L*a*b* colors"
  process:  "Print the line with its Delta E like 42.2,67,-23.3,55,30,2,19.915620026396260067235315007755 for each line"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/pro"
  n_csv_lines: 10000000

jobs:
  test-implementation-de00-pro:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📂 For each step below, a new shell will be started at the repository root
        uses: actions/checkout@v5

      - name: 👉 Disable the user manual database, which is not needed in this CI/CD workflow
        run: sudo ln --backup --symbolic --verbose $(which true) $(which mandb)

      - name: 👉 Set up a less crowded server for the APT package manager (step disabled, but useful when an installation is slow)
        run: true || grep -Flr '.ubuntu.com' /etc/apt | xargs sudo sed -i 's|[^/]\+ubuntu.com|mirrors.maine.edu|g'

      - name: 📦 Set up SWI-Prolog and GCC
        run: |
          command -v swipl > /dev/null || { sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes swi-prolog ; }
          command -v gcc > /dev/null || { sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes gcc ; }
          swipl --version && gcc --version

      - name: ⚙️ Compile CIEDE2000 tester in Prolog
        run: swipl -O -q -g true -t halt --stand_alone=true -o driver-pro -c tests/pro/ciede-2000-driver.pro

      - name: ⚙️ Compile the CIEDE2000 driver program in C99
        run: gcc -std=c99 -Wall -pedantic -O2 -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: 📑 Display help for the authoritative test software
        run: ./ciede-2000-driver --help

      - name: 🎨 Generate ΔE2000 color difference test cases
        run: |
          # Splits the large file into as many smaller files as there are vCPUs
          n_cpu=$(nproc) && ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines |
          split --unbuffered --lines=$(( ($n_csv_lines + $n_cpu - 1) / $n_cpu )) --numeric-suffixes=1 --additional-suffix=.csv - test-cases-
          # Shows the name, size and first line of newly created files
          du -h test-cases-* | awk '{getline line < $2; print $2, "(" $1 "B) contains L*a*b* color pairs for vCPU " NR ", first values =", line}'

      - name: ⚡ Solves test cases by calculating ΔE2000 in Prolog (parallelized operation)
        run: |
          for file in test-cases-*; do
            ./driver-pro $file > solved-$file &
            echo "Processes $file ($(wc -l < $file) lines) in parallel ➤ solved-$file"
          done
          wait

      - name: 🚀 Check that C99 calculations matches Prolog’s
        run: cat solved-* | ./ciede-2000-driver -o summary.txt

      - name: 🔍 Display verification output
        run: cat summary.txt

      - name: 🏁 Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "✔️ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "❌ Verification failed. See above for details."
            exit 1
          fi
