name: ΔE2000 against My FreeBasic Framework in VBA

on:
  schedule:
    - cron: '16 15 9,23 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard checks the Delta E 2000 against My FreeBasic Framework calculations."
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/bas"

jobs:
  test-delta-e-2000-my-freebasic-framework:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up FreeBASIC Compiler version 1.10.1 released on 2023-12-24
        run: |
          params="-q -T5 -t1"
          ########################################################################################
          ####  STEP 1:                          Install Dependencies                         ####
          ########################################################################################
          wget $params http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb    -O X.deb ||
          wget $params http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb   -O X.deb
          sudo apt-get update
          sudo apt-get install ./X.deb
          ########################################################################################
          ####  STEP 2:                     Download & Extract FreeBASIC                      ####
          ########################################################################################
          wget $params https://users.freebasic-portal.de/freebasicru/user-files/FreeBASIC-1.10.0-linux-x86_64.tar.gz  -O X.tar.gz ||
          wget $params https://local.doublebyte.ru/static/FreeBASIC-1.10.1-linux-x86_64.tar.gz                        -O X.tar.gz ||
          wget $params http://downloads.sourceforge.net/fbc/FreeBASIC-1.10.1-linux-x86_64.tar.gz?download             -O X.tar.gz ||
          wget $params https://github.com/engineer-man/piston/releases/download/pkgs/freebasic-1.9.0.pkg.tar.gz       -O X.tar.gz
          tar -xf X.tar.gz
          ########################################################################################
          ####  STEP 3:                     Add FreeBASIC to System PATH                      ####
          ########################################################################################
          fbc_dir=$(ls -1d Free* 2>/dev/null | head -n 1)
          ln -s $PWD/$fbc_dir/bin/fbc /usr/local/bin/fbc
          ########################################################################################
          ####  CONCLUSION:               FreeBASIC Installed in Under 15s                    ####
          ########################################################################################
          rm X* && printf '\n\n\n\n' && fbc --version

      - name: 🔧 Initialize the FreeBASIC source file
        run: |
          ####################################################################
          ######    1. Inject the compatible function in FreeBASIC      ######
          ####################################################################
          printf '%s\n' '' \
          'Const PI = 3.14159265358979323846' \
          'Type Lab' \
          '	As Double L, a, b' \
          'End Type' \
          'Function ciede_2000_other(l_1 As Double, a_1 As Double, b_1 As Double, l_2 As Double, a_2 As Double, b_2 As Double) As Double' \
          '	Dim Lab1 As Lab = ( l_1, a_1, b_1 )' \
          '	Dim Lab2 As Lab = ( l_2, a_2, b_2 )' \
          '' > ciede-2000-vs-my-freebasic-framework.bas

          url="https://raw.githubusercontent.com/XusinboyBekchanov/MyFbFramework"
          url="$url/cda7c0b6a353c95f70455e90860cb5158a0e56d4/inc/CSDDC.bi"
          wget -q -T5 -t1 "$url" -O- | sed -n '395,427p' >> ciede-2000-vs-my-freebasic-framework.bas

          ####################################################################
          ######      2. Inject the native function  in FreeBASIC       ######
          ####################################################################
          sed -n '/ciede_2000/,$p' ciede-2000.bas >> ciede-2000-vs-my-freebasic-framework.bas

          ####################################################################
          ######           3. Generate random L*a*b* colors             ######
          ######              and display ΔE2000 deviations             ######
          ####################################################################
          printf '%s\n' '' \
          'Dim as Integer n_iterations = Val(Command(1))' \
          'Dim as Double max_err = 0.0, l1, a1, b1, l2, a2, b2, d1, d2, deviation' \
          'Randomize Timer' \
          'For i as Integer = 0 to n_iterations - 1' \
          '	l1 = Rnd * 100.0' \
          '	a1 = Rnd * 256.0 - 128.0' \
          '	b1 = Rnd * 256.0 - 128.0' \
          '	l2 = Rnd * 100.0' \
          '	a2 = Rnd * 256.0 - 128.0' \
          '	b2 = Rnd * 256.0 - 128.0' \
          '	d1 = ciede_2000(l1, a1, b1, l2, a2, b2)' \
          '	d2 = ciede_2000_other(l1, a1, b1, l2, a2, b2)' \
          '	deviation = Abs(d2 - d1)' \
          '	If max_err < deviation then' \
          '		max_err = deviation' \
          '		Print "Greatest deviation of"; deviation; " in color differences at iteration"; (i + 1); "."' \
          '	End If' \
          'Next' \
          'If max_err < 1.0E-10 Then End 0 Else End 1 End If' \
          '' >> ciede-2000-vs-my-freebasic-framework.bas

      - name: ☁ Save source code on a remote server for monitoring (optional step)
        run: ${{ secrets.SAVE_ARTIFACT }} auto=@ciede-2000-vs-my-freebasic-framework.bas || true

      - name: ⚙️ Compile the FreBASIC test program
        run: fbc -O 2 ciede-2000-vs-my-freebasic-framework.bas

      - name: 🚀 Execute a large amount of ΔE2000 test cases in FreeBASIC
        run: ./ciede-2000-vs-my-freebasic-framework 50000000
