name: ΔE2000 against Rust palette

on:
  schedule:
    - cron: '8 6 11,25 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard checks the Delta E 2000 with the Rust palette crate."
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/rs"

jobs:
  test-delta-e-2000-palette:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up Rust
        run: |
          command -v rustc > /dev/null || {
            wget --timeout=5 --tries=3 -qO- https://sh.rustup.rs | sh -s -- --profile minimal -y
            source $HOME/.cargo/env
          }

      - name: 🔧 Initialize Cargo project
        run: |
          rustc --version && cargo --version
          cargo new demo
          cp -p tests/rs/vs-palette.rs demo/src/main.rs
          echo 'rand = "0.9"' >> demo/Cargo.toml
          echo 'num-traits = "0.2"' >> demo/Cargo.toml
          echo 'palette = "0.7.6"' >> demo/Cargo.toml

      - name: 🚀 Execute a large amount of ΔE2000 test cases in Rust
        run: cargo run --manifest-path=demo/Cargo.toml --release -- 400000000
