name: ΔE2000 against shades in R

# When this workflow was tested, its execution produced a success in 158 seconds.

on:
  schedule:
    - cron: '15 12 11,25 * *'
  workflow_dispatch:

env:
  description: "Automated Testing — Michel Leonard checks the Delta E 2000 with shades (a Practical Tool for Color Theory in R)."
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/r"

jobs:
  test-delta-e-2000-shades:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📂 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Set up R
        uses: r-lib/actions/setup-r@v2
        continue-on-error: true
        timeout-minutes: 3

      - name: 📦 Set up Rscript (alternative)
        run: command -v Rscript > /dev/null || { sudo apt-get update && sudo apt-get install -y r-base ; }

      - name: 🔧 Initialize the R source file
        run: |
          Rscript -e 'cat("R version:", R.version.string, "\n")'

          printf '%s\n' 'ciede_2000_other <- function (L1, a1, b1, L2, a2, b2) {' \
          '	deg2rad <- function(x) x / 180 * pi' \
          '	rad2deg <- function(x) x / pi * 180' > delta-e-2000-vs-shades.r

          wget -q -T5 -t1 https://raw.githubusercontent.com/jonclayden/shades/5149b07f393ac7bc3054b65e27b3831e40935610/R/distance.R -O- |
          sed -n '/LBarPrime/,$p' >> delta-e-2000-vs-shades.r

          cat ciede-2000.r >> delta-e-2000-vs-shades.r

          printf '%s\n' 'args <- commandArgs(trailingOnly = TRUE)' \
          'n_calls <- if (length(args) < 1) 1000 else as.numeric(args[1])' \
          'n_1 <- 2 ** 20' \
          'n_2 = ceiling(n_calls / n_1)' \
          'max_err <- 0' \
          'for (i in 1:n_2) {' \
          '	n <- if (i == 1 && n_calls != n_1) n_calls %% n_1 else n_1' \
          '	l1 <- runif(n, min = 0.0, max = 100.0)' \
          '	a1 <- runif(n, min = -128.0, max = 128.0)' \
          '	b1 <- runif(n, min = -128.0, max = 128.0)' \
          '	l2 <- runif(n, min = 0.0, max = 100.0)' \
          '	a2 <- runif(n, min = -128.0, max = 128.0)' \
          '	b2 <- runif(n, min = -128.0, max = 128.0)' \
          '	d1 <- ciede_2000(l1, a1, b1, l2, a2, b2)' \
          '	d2 <- ciede_2000_other(l1, a1, b1, l2, a2, b2)' \
          '	err <- max(abs(d2 - d1))' \
          '	if (max_err < err)' \
          '		max_err <- err' \
          '}' \
          'has_error <- 1E-10 < max_err' \
          'cat("The largest deviation measured after", as.integer(n_calls), "calculations is", max_err, "so this test is", if (has_error) "FAILED." else "PASSED.")' \
          'quit(status = as.integer(has_error))' >> delta-e-2000-vs-shades.r

      - name: ☁ Save source code on a remote server for monitoring (optional step)
        run: ${{ secrets.SAVE_ARTIFACT }} auto=@delta-e-2000-vs-shades.r || true

      - name: 🚀 Execute a large amount of ΔE2000 test cases in R
        run: Rscript delta-e-2000-vs-shades.r 100000000
